### ISSUE TITLE
Message not selected when not in Inbox

### ISSUE THREAD

**Issue by halvorlu** [poohsen/thunderlink#23]
It seems that if Thunderlink is set to select a message when opening a thunderlink, it is only selected if it is located in the Inbox. If Thunderlink is set to open the message in a new window, it works as expected.

**Comment by poohsen** [comment]
Have you tried this with several emails? Is it imap or pop? anything unusual about the folder names that wouldn't work for you?
I tested this when I first created TL. I'll have to retest

**Comment by halvorlu** [comment]
I don't seem to be able to reproduce the problem now. I might have been wrong. Sorry for the inconvenience!
