### ISSUE TITLE
Feature Request: also accept message-URIs

### ISSUE THREAD

**Issue by flenzen** [poohsen/thunderlink#27]
Is it possible also to accept the message-URI scheme as used by Apple Mail, i. e. links of the form `message://<Message-ID>` or `message:<Message-ID>` such that links embedded in mails can be at least also used by people using Apple Mail?

**Comment by riedel** [comment]
This is the standard (sic) way: `mid:<Message-ID>` according to https://www.ietf.org/rfc/rfc2392.txt
`cid:` support would be great too...

**Comment by riedel** [comment]
just for cross-reference: https://bugzilla.mozilla.org/show_bug.cgi?id=264270, http://superuser.com/questions/681421/what-email-clients-support-cid-and-mid-uris
