### ISSUE TITLE
Some thunderlinks fail, due to .desktop file error

### ISSUE THREAD

**Issue by artumi-richard** [poohsen/thunderlink#32]
Hi

Thanks for making this super useful add-on. I find it really useful.
I have come across an issue, and I think I have the solution. 
In short I thing the .desktop file needs to have 

`Exec=thunderbird` -thunderlink '%u'
instead of 
`Exec=thunderbird` -thunderlink %u 

Details:

Thunderbird is failing to find an email. The email is in an IMAP mailbox, and exists.
If I make a new thunderlink the link is
`thunderlink://messageid=010c01d1dc25$9790e090$c6b2a1b0$@wiki-solutions.com`
If I then search for that link it fails to find it with the message:
"Couldn't find an email message for ThunderLink
thunderlink://messageid=010c01d1dc25790e090wiki-solutions.com"
You will see that the $ and @ symbols are missing in the message.
I'm using VimWiki, and pass requests to xdg-open and can confirm that the same error is produced by:
`xdg-open thunderlink://messageid=010c01d1dc25$9790e090$c6b2a1b0$@wiki-solutions.com`
I also confirm that other messages are opening correctly, for example:
`thunderlink://messageid=058fc31c-b487-8be1-040e-9472587e73c8@artumi.com
I've traced it down to the lack of single quotes, since when added, this works:
`thunderbird -thunderlink 'thunderlink://messageid=010c01d1dc25$9790e090$c6b2a1b0$@wiki-solutions.com'
So I changed the Exec line in the file "/usr/share/applications/thunderbird-tl.desktop" to this:

Exec=thunderbird -thunderlink '%u'

And that seems to have solved the problem.

Also, I thought it may be useful for other vimwiki users to have this bit of code, which, once placed in their .vimrc file will enable thunderlinks to work in the way they would expect.  I've made a gist that you may want to put somewhere useful.

https://gist.github.com/artumi-richard/f5545b104e97a9ae444404d9b98f4b95

Thanks

**Comment by poohsen** [comment]
thanks! I updated the readme.
