### ISSUE TITLE
README file is ambiguous

### ISSUE THREAD

**Issue by sorenoneill** [poohsen/thunderlink#34]
The installation instruction for Ubuntu Natty-and-newer is ambiguous:

> 2. then, make a copy of your ~/.local/share/applications/thunderbird.desktop and name it thunderbird-tl.desktop
> 3. Change the line that starts with Exec=thunderbird %u... to Exec=thunderbird -thunderlink '%u'...
> 4. and the line that starts with MimeType=... to MimeType=x-scheme-handler/thunderlink; this entry for Thunderbird will thus serve only for handling ThunderLinks.

In bullets 3. and 4. it is not clear whether it is the original thunderbird.desktop file which should be edited, or the new thunderbird-tl.desktop file

**Comment by poohsen** [comment]
True. I mean the latter. Will update the description
