### ISSUE TITLE
Cannot create thunderlinks after upgrade from 45.8.0 to 52.0.1 or 52.1.0

### ISSUE THREAD

**Issue by kgorlen** [poohsen/thunderlink#35]
Cannot create thunderlinks using either the drop-down menu or CTL-ALT-n hot keys after upgrade from 45.8.0 -- nothing happens.

**Comment by JotaPin** [comment]
Same issue here, not working anymore with thunderbird 52.1.1 (a pitty, it is very useful!!)

**Comment by poohsen** [comment]
This repository is no longer maintained. I won't take the time to update thunderlink so it works with newer versions of TB. My apologies.
